apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: LoadBalancer  # Or LoadBalancer if needed
  ports:
    - port: {{ .Values.service.port }}               # External port that users access
      targetPort: {{ .Values.service.targetPort }}        # The port on the container (same as containerPort in deployment.yaml)
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
